print("Freatures of Python:")
print("\n\t1.Easy to learn and Use")
print("\t\t-simple syntax similar to English")
print("\t2.Ipnterprited language")
print("\t\t-Executes code line by line")
print("\t3.Dinamically Typed")
print("\t\t-No need to declare variable")
print("\t4.Extensive Libraries")
print("\t\t-Supports  many built-in and third-party libraries")
print("\t5.Portable")
print("\t\t-Runs on different platforms without changes")
print("\t6.Object oriented ")
print("\t\t-Supprots classes and objects")
print("\t7.open Source")
print("\t\t-Free to use and Distribute")
print("\t8.High level Language")
print("\t\t-Abstract complex details from the programer")
print("\n Start exploring python Today!")
